- name: ngrok get repo key
  ansible.builtin.get_url:
    url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
    dest: /etc/apt/keyrings/ngrok.asc

- name: ngrok add repo
  ansible.builtin.apt_repository:
    # To Do: map the Debian version 'bullseye' to corresponding ubuntu version provided by {{ ansible_distribution_release }}
    repo: "deb [trusted=yes signed-by=/etc/apt/keyrings/ngrok.asc] https://ngrok-agent.s3.amazonaws.com bullseye main"
    state: present

- name: ngrok install
  ansible.builtin.apt:
    name: ngrok
    update_cache: true

- name: ngrok create system user
  ansible.builtin.user:
    name: ngrok
    system: true
    home: /etc/ngrok
    create_home: true
    shell: /usr/sbin/nologin
    password: "!"
    
- name: ngrok make config dir
  ansible.builtin.file:
    path: /etc/ngrok/
    state: directory
    owner: ngrok
    group: ngrok

- name: ngrok user config setup
  template:
    src: ngrok_config.j2
    dest: "/etc/ngrok/ngrok.yml"

- name: ngrok user systemd service
  template:
    src: ngrok_systemd_service.j2
    dest: "/lib/systemd/system/ngrok@.service"
  register: setup_ngrok_config

- name: ngrok restart service
  ansible.builtin.systemd:
    name: ngrok@{{item}}.service    #name after the @ must match the name of the endpoint in the config 
    scope: user
    daemon_reload: true
    state: restarted
    enabled: true
  loop: "{{ ngrok_endpoints }}"
  when: setup_ngrok_config.changed