- name: ngrok create system user
  ansible.builtin.user:
    name: ngrok
    system: true
    home: /var/lib/ngrok
    create_home: true
    shell: /usr/sbin/nologin
    password: "!"

- name: ngrok install via apt
  block:
    - name: ngrok add an apt signing key
      ansible.builtin.get_url:
        url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
        dest: /etc/apt/trusted.gpg.d/ngrok.asc

    - name: ngrok add repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://ngrok-agent.s3.amazonaws.com bookworm main"
        state: present

    - name: ngrok install ngrok
      ansible.builtin.apt:
        name: ngrok
        state: latest
        update_cache: true

- name: ngrok make config dir
  ansible.builtin.file:
    path: /etc/ngrok/
    state: directory
    owner: ngrok
    group: ngrok

- name: ngrok user config setup
  template:
    src: ngrok_config.j2
    dest: "/etc/ngrok/ngrok.yml"
    owner: ngrok
    group: ngrok

- name: ngrok systemd service
  template:
    src: ngrok_systemd_service.j2
    dest: "/lib/systemd/system/ngrok.service"
  register: setup_ngrok_config

- name: ngrok restart service
  ansible.builtin.systemd:
    name: ngrok.service
    daemon_reload: true
    state: restarted
    enabled: true
  when: setup_ngrok_config.changed