- name: obsserver obs studio setup
  # https://obsproject.com/kb/linux-installation
  # https://github.com/pschmitt/obs-cli
  block:
    - name: obs studio add apt repo
      ansible.builtin.apt_repository:
        repo: ppa:obsproject/obs-studio

    - name: obs studio install
      ansible.builtin.apt:
        update_cache: yes
        name: "obs-studio={{obsserver_obs_studio_version}}"
        # versions: https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio

    - name: obs studio create autostart directory
      ansible.builtin.file:
        state: directory
        dest: "/home/{{obsserver_user}}/.config/autostart/"

    - name: obs studio autostart
      ansible.builtin.copy:
        src: obs.desktop
        dest: "/home/{{obsserver_user}}/.config/autostart/obs.desktop"

    - name: obs studio cli install
      when: false
      community.general.pipx:
        name: obs-cli
        include_injected: false
        state: install
        python: 3.12

 #   - name: obs install websocket plugin
 #   This is no longer necessary on the latest versions of obs

#    - name: start obs on boot
#      block:
#        - name: 

    - name: obs studio shared data directory
      block:
        - name: obs studio create data directory mount point
          ansible.builtin.file:
            path: /var/opt/obs-server/
            state: directory

        - name: obs studio mount shared data directory
          ansible.posix.mount:
            path: /var/opt/obs-server/
            src: obs_data
            fstype: virtiofs
            state: present      