# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-remote-tunnel/
- name: cloudflared get cloudflare repo apt key
  ansible.builtin.apt_key:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg 
    state: present

- name: cloudflared add apt repo remove
  ansible.builtin.apt_repository:
    repo: "deb https://pkg.cloudflare.com/cloudflared noble main"
    state: absent

- name: cloudflared add apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://pkg.cloudflare.com/cloudflared jammy main"
      # ubuntu 24 "noble" does not have an official release.
      # See github issue
      # Temporarily using 'jammy'
      # https://github.com/cloudflare/cloudflared/issues/1235

- name: cloudflared install packages
  ansible.builtin.apt:
    name: cloudflared
    state: present
    update_cache: yes

- name: create cloudflare tunnel config
  debug: msg='To Do'
  when: false

- name: install cloudflare tunnel service
  shell: cloudflared install service
  when: false

