#!/bin/bash

# This script prepares a fresh server to be configured with ansible

set -euo pipefail

# To Do: Check for existing versions of dependencies

echo -e '\n\n\n'
echo 'Installing ansible dependencies'
sudo apt update
sudo apt install -y \
   git \
   python3.12 \
   pipx \
   jq
echo 'Dependencies installed'


echo -e '\n\n\n'
echo 'Installing github cli'
if which gh ; then
    echo "github cli installed"
else
    (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
      && sudo mkdir -p -m 755 /etc/apt/keyrings \
      && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
      && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      && sudo apt update \
      && sudo apt install gh -y
fi

echo -e '\n\n\n'
echo 'Installing Ansible'
pipx install --include-deps ansible
pipx ensurepath
echo 'Ansible installed'

echo -e '\n\n\n'
echo 'You can now complete the rest of the server configuration with ansible'
