- name: single-user-kiosk configure base os
  block:
  - name: single-user-kiosk set hostname
    when: single_user_kiosk_hostname is defined
    ansible.builtin.hostname:
      name: "{{single_user_kiosk_hostname}}"
      use: systemd

  - name: single-user-kiosk create primary user
    ansible.builtin.user:
      name: "{{single_user_kiosk_primary_user}}"
      shell: /bin/bash
      groups: video,render
      append: yes

  - name: single-user-kiosk add ssh public key
    ansible.posix.authorized_key:
      user: "{{single_user_kiosk_primary_user}}"
      state: present
      key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/streambox-admin.pub') }}"
    
  - name: single-user-kiosk install ssh
    ansible.builtin.apt:
      pkg:
        - openssh-server

- name: single-user-kiosk configure desktop
  block:
  - name: single-user-kiosk disable screensavers packages and locks
    copy:
      src: no-screen-lock
      dest: /etc/apt/preferences.d/no-screen-lock

  - name: single-user-kiosk install desktop environment
    ansible.builtin.apt:
      pkg:
        - xfce4
        - xfce4-goodies
        - lightdm

  - name: single-user-kiosk create home bin directory
    ansible.builtin.file:
      path: "/home/{{single_user_kiosk_primary_user}}/.local/bin/"
      state: directory
      mode: '0755'
      owner: "{{single_user_kiosk_primary_user}}"
      group: "{{single_user_kiosk_primary_user}}"

  - name: single-user-kiosk disable screen blank settings xfconfquery
    become: true
    become_user: "{{single_user_kiosk_primary_user}}"
    ansible.builtin.copy:
      src: xfce4-disable-screen-blank.sh
      dest: "/home/{{single_user_kiosk_primary_user}}/.local/bin/xfce4-disable-screen-blank.sh"
      mode: 0755

  # ToDO make display settings more robust
  # https://github.com/afrohlich/kqsfl_streaming/issues/1
  - name: single-user-kiosk disable screen blank settings xset
    ansible.builtin.blockinfile:
      path: /home/stream-admin/.profile 
      prepend_newline: true
      marker: "# Disable Screen Blanking and Display Power Management"
      block: |
        xset -display :0 s off && xset -display :0 s noblank
        xset -display :0 -dpms
        xset -display :0 q
        $HOME/.local/bin/xfce4-disable-screen-blank        

  - name: single-user-kiosk disable screen blank settings xorg
    ansible.builtin.copy:
      src: 10-disable-screen-blank.conf
      dest: /etc/X11/xorg.conf.d/10-disable-screen-blank.conf

- name: single-user-kiosk auto-login
  ansible.builtin.template:
    src: autologin.conf.j2
    dest: /etc/lightdm/lightdm.conf.d/12-autologin.conf

- name: single-user-kiosk install essential tools
  block:
    - name: single-user-kiosk install essential tools
      ansible.builtin.apt:
        pkg: firefox