#!/bin/bash

adisplay=$1
xmcookie='/run/lightdm/root/:$1'
## Xauth notes:
# xauth for lightdm -> /var/run/lightdm/root/\:0
username=`who | grep "(:${adisplay})" | awk '{print $1}'`

if [ ! -f $xmcookie ] & [ ! -z "$username" ]; then
    xmcookie=/home/$username/.Xauthority
else
    if [ ! -f $xmcookie ] & [ -z "$username" ]; then
        xmcookie=/var/lib/lightdm/.Xauthority
    fi
fi

/usr/bin/x11vnc -display WAIT:%i \
   -find -env FD_XDM=1 -auth $xmcookie \
   -listen localhost -no6 \
   -forever -shared -loop -nolookup -noxdamage -repeat \
   -rfbauth /etc/x11vnc/x11vnc.passwd \
   -rfbport 5900

exit $?