streambox_admin_user: stream-admin
streambox_admin_password: "{{ undef() }}" # Must set before role execution
streambox_admin_user_pubkey: "{{ undef() }}"

streambox_timezone: 'America/New_York'

streambox_obs_admin_user: "{{streambox_admin_user}}"
streambox_obs_admin_password: admin
streambox_obs_admin_user_pubkey: "{{ streambox_admin_user_pubkey }}"

streambox_obs_virtualized: true

streambox_config_dir: /etc/streambox

streambox_rclone_version: 1.68.1
streambox_rclone_config_dir: "{{streambox_config_dir}}/remote-backends/"
streambox_rclone_remote_root_folder: "/obs"
streambox_rclone_mount_point: /var/opt/obs_server

streambox_obs_studio_version: 29.1.3-0obsproject1~focal

streambox_ngrok_public_url: "{{ undef() }}" # Must set before role execution

streambox_kasmvnc_version: 1.3.3

streambox_ttyd_port: 8082

streambox_refresh_vm_isos: false

streambox_twitch_api_token: "{{ undef() }}" # Must set before role execution
streambox_github_token: "{{ undef() }}" # Must set before role execution

streambox_ngrok_token: "{{ undef() }}" # Must set before role execution

streambox_influxdb_token: "{{ undef() }}"
streambox_influxdb_org_name: "streambox"

streambox_vnc_user: "{{ stream_admin_user }}" # Must set before role execution
streambox_vnc_password: "{{ undef() }}" # Must set before role execution