#!/bin/bash

# This script outlines the arguments to building a bootable iso

# Reference Links
# https://help.ubuntu.com/community/LiveCDCustomization
# https://wiki.debian.org/RepackBootableISO

set -xeuo pipefail

script_dir=$(realpath $(dirname $0))
base_iso_url="https://releases.ubuntu.com/20.04.6/ubuntu-20.04.6-live-server-amd64.iso"
base_iso_name=$(echo $base_iso_url | sed 's/.*\///')
build_dir=/tmp/streambox_iso/
base_iso="$iso_build_dir/$base_iso_name"
iso_mount_dir="$build_dir/isomount"
iso_build_dir="$build_dir/extracted"
squashfs_dir="$build_dir/squashfs-root"
squashfs_update_script=


autoinstall_configs=$script_dir/autoinstall
grub_cfg="$script_dir/grub.cfg"
isolinux_txt_cfg="$script_dir/isolinux.txt.cfg"


cleanup_squashfs() {
    umount $squashfs_dir/run
    rm $squashfs_dir
}

cleanup() {
    echo cleaning up
    if [ -e "$squashfs_dir" ] ;  then
	echo cleaning up squashfs
        cleanup_squashfs
    fi

    if [ -e "$iso_build_dir" ] ; then
        echo "Removing $iso_build_dir"
        rm -r $iso_build_dir
    fi
    
    umount $iso_mount_dir
}

trap cleanup EXIT

if ! [ -e "$base_iso" ] ; then
    echo "Downloading $iso_base_url as $base_iso"
    wget -O $base_iso $iso_base_url
fi

mount -o loop $base_iso $iso_mount_dir
mkdir $iso_build_dir
rsync -a $iso_mount_dir $iso_build_dir


cp $autoinstall_cfg_dir  $iso_build_dir/subiquity.autoinstall
cp $grub_cfg  $iso_build_dir/grub/grub.cfg
cp $isolinux_txt_cfg  $iso_build_dir/isolinux/txt.cfg


if ! [ -z "$squashfs_update_script" ] ;  then
    echo "Configuring squashfs for iso"
    unsquashfs -dest $squashfs_dir $iso_mount_dir/casper/filesystem.squashfs
    cp /etc/hosts $squashfs_dir/etc/hosts
    mount -o bind /run/ $squashfs_dir/run
    mount --bind /dev/ $squashfs_dir/dev

    chroot $squashfs_dir $squashfs_update_script

else
    echo "Skipping squashfs config. No squashfs update script supplied"
fi


# Example options generated by using
# sudo xorriso -indev ~/Downloads/ubuntu-20.04.6-live-server-amd64.iso -report_el_torito cmd

# full xorriso options
# https://www.gnu.org/software/xorriso/man_1_xorriso.html


if [ -z "$iso_build_dir" ] ; then
    echo iso build dir is required
    exit
fi 


xorriso \
  -outdev streambox-autoinstall.iso \
  -map $iso_build_dir / -- \
  -volid 'StreamboxISO' \
  -boot_image any partition_cyl_align=off \
  -boot_image any partition_offset=0 \
  -boot_image any mbr_force_bootable=on \
  -boot_image any apm_block_size=2048 \
  -boot_image any iso_mbr_part_type=0x00 \
  -boot_image any cat_path='/isolinux/boot.cat' \
  -boot_image isolinux bin_path='/isolinux/isolinux.bin' \
  -boot_image any platform_id=0x00 \
  -boot_image any emul_type=no_emulation \
  -boot_image any load_size=2048 \
  -boot_image any boot_info_table=on \
  -boot_image any next \
  -boot_image any efi_path='/boot/grub/efi.img' \
  -boot_image any platform_id=0xef \
  -boot_image any emul_type=no_emulation \
  -boot_image any load_size=4161536 \
  -boot_image isolinux partition_entry=gpt_basdat \
  -boot_image isolinux partition_entry=apm_hfsplus 
