
# https://wiki.archlinux.org/title/LightDM
# https://wiki.archlinux.org/title/I3
# https://unix.stackexchange.com/questions/86221/how-can-i-lock-my-screen-in-gnome-3-without-gdm

- name: desktop preseed dpkg questions
  ansible.builtin.debconf:
    name: "{{item.name}}"
    question: "{{item.question}}"
    value: "{{item.value}}"
    vtype: "{{item.vtype}}"
  loop:
    - name: lightdm
      question: shared/default-x-display-manager
      value: lightdm
      vtype:  select
  no_log: false

- name: desktop install packages
  ansible.builtin.apt:
    pkg:
      - lightdm
      - light-locker
      - i3
      - i3lock

- name: lightdm set default desktop manager
  ansible.builtin.expect:
    command: /usr/sbin/dpkg-reconfigure -f readline lightdm
    responses:
        "Default display manager:":
            - "lightdm"

- name: disable wayland
  ansible.builtin.lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^WaylandEnable='
    insertafter: '^#WaylandEnable='
    line: 'WaylandEnable=false'

- name: disable screen lock an lid close
  # https://askubuntu.com/questions/1014965/automatic-suspend-computer-will-suspend-very-soon-because-of-inactivity-ho
  # https://www.tecmint.com/disable-suspend-and-hibernation-in-linux/
  ansible.builtin.blockinfile:
    path: /etc/systemd/logind.conf
    insertafter: '^[Login]'
    marker: "# {mark} - ANSIBLE BLOCK - Lid autolock #"
    block: |
      HandleLidSwitch=ignore 
      HandleLidSwitchDocked=ignore
      
- name: disable global suspend
  become_user: gdm
  shell: |
    dbus-launch --exit-with-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
    dbus-launch --exit-with-session gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'nothing'

- name: disable stream-admin suspend
  become_user: stream-admin
  shell: |
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
    gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'nothing'

#- name: set screen size
#  command: xrandr --output `xrandr -q | grep -w connected | cut -d' ' -f1` --mode 1440x900

- name: desktop disable gnome init
  ansible.builtin.apt:
    name: gnome-initial-setup
    state: absent
    purge: true

- name: desktop setup reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600
