- name: streambox configure base os
  import_tasks: components/base-os.yml
  tags: streambox_configure_base_os

- name: streambox configure rclone backend for obs data
  import_role:
    name: rclone
  vars:
    rclone_mount_name: "streambox-backend"
    rclone_mount_subdir: "{{streambox_rclone_remote_root_folder}}"
    rclone_mount_point: "{{streambox_rclone_mount_point}}"
    rclone_config_dir: "{{streambox_rclone_config_dir}}"
    rclone_mount_user: "{{streambox_admin_user}}"
  tags: streambox_configure_rclone_backend

- name: streambox configure libvirt hypervisor for obs server
  import_tasks: components/obs-libvirt.yml
  tags: streambox_configure_libvirt_stack

- name: streambox_configure obs-server
  when: streambox_single_server  ##  Disabling this for now
  block:
    - import_role:
        name: obs-server
      when: streambox_single_server is defined and not streambox_single_server
      delegate_to: obs-server
      ### This host must be defined in the inventory
      ### MAKE SURE THE SSH PROXY SETTINGS ARE CORRECTLY SET

    - import_role:
        name: obs-server
      when: streambox_single_server is defined and not streambox_single_server
  tags: streambox_configure_obs_server

- name: streambox configure docker compose stack
  import_tasks: components/docker-stack.yml
  tags: streambox_configure_docker_compose_stack

- name: streambox configure remote access
  import_tasks: components/remote-web-access.yml
  tags: streambox_configure_remote_access
