- name: streambox config directory
  ansible.builtin.file:
    path: "{{streambox_config_dir}}"
    state: directory
    mode: '0755'
    owner: "{{streambox_admin_user}}"
    group: "{{streambox_admin_user}}"

- name: streambox configure base os
  import_tasks: components/base-os.yml
  tags: streambox_configure_base_os

- name: streambox configure rclone backend for obs data
  import_role:
    name: rclone
  vars:
    rclone_mount_name: "streambox-backend"
    rclone_mount_subdir: "{{streambox_rclone_remote_root_folder}}"
    rclone_mount_point: "{{streambox_rclone_mount_point}}"
    rclone_config_dir: "{{streambox_rclone_config_dir}}"
    rclone_mount_user: "{{streambox_admin_user}}"
  tags: streambox_configure_rclone_backend

- name: streambox configure obs-server
  when: false  # disabled for now
  block:
    - name: streambox configure obs desktop environment
      import_role:
        name: single-user-kiosk
      delegate_to: "{{ 'obs-server' if streambox_obs_virtualized else omit }}"

    - name: streambox configure obs-server
      import_role:
        name: obs-server
      vars:
        obsserver_is_virtualized: true
      delegate_to: "{{ 'obs-server' if streambox_obs_virtualized else omit }}"
      tags: streambox_configure_obs_server
      ### 'obs-server' host must be defined in the inventory
      ### MAKE SURE THE SSH PROXY SETTINGS ARE CORRECTLY SET
  
- name: streambox configure docker compose stack
  import_tasks: components/docker-stack.yml
  tags: streambox_configure_docker_compose_stack

- name: streambox configure ngrok remote web access
  import_role:
    name: ngrok
  vars:
    url: "{{ngrok_public_url}}"
  tags: streambox_configure_remote_access

- name: streambox remote tty access
  block:
    - name: steambox remote tty setup
      # https://github.com/tsl0922/ttyd
      block:
        - name: ttyd install
          ansible.builtin.snap:
            name: ttyd
            classic: true

        - name: ttyd systemd service install
          ansible.builtin.template:
            src: ttyd_systemd_root_service.j2
            dest: /etc/systemd/system/ttyd.service

        - name: ttyd systemd service enable
          ansible.builtin.systemd:
            name: ttyd.service
            enabled: true
            daemon_reload: true
            state: restarted

- name: strambox configure logging and monitoring
  import_tasks: components/logging-monitoring.yml
  tags: streambox_configure_monitoring

- name: streambox configure libvirt hypervisor for obs server
  import_tasks: components/obs-libvirt.yml
  when: streambox_obs_virtualized
