- name: streambox configure base os
  import_tasks: components/base-os.yml

- name: streambox configure rclone backend for obs data
  import_role:
    name: rclone
  vars:
    rclone_mount_name: "streambox-backend"
    rclone_mount_subdir: "{{streambox_rclone_remote_root_folder}}"
    rclone_mount_point: "{{streambox_rclone_mount_point}}"
    rclone_config_path: "{{streambox_rclone_config_dir}}"

- name: streambox configure libvirt hypervisor for obs server
  import_tasks: components/obs-libvirt.yml

- name: streambox configure docker compose stack
  import_tasks: components/docker-stack.yml