- name: streambox configure base os
  import_tasks: components/base-os.yml
  tags: streambox_configure_base_os

- name: streambox configure rclone backend for obs data
  import_role:
    name: rclone
  vars:
    rclone_mount_name: "streambox-backend"
    rclone_mount_subdir: "{{streambox_rclone_remote_root_folder}}"
    rclone_mount_point: "{{streambox_rclone_mount_point}}"
    rclone_config_dir: "{{streambox_rclone_config_dir}}"
    rclone_mount_user: "{{streambox_admin_user}}"

- name: streambox configure libvirt hypervisor for obs server
  import_tasks: components/obs-libvirt.yml
  tags: streambox_configure_libvirt_stack

- name: streambox configure docker compose stack
  import_tasks: components/docker-stack.yml
  tags: streambox_configure_docker_compose_stack

- name: streambox configure remote access
  import_tasks: components/remote-web-access.yml
  tags: streambox_configure_remote_access
