version: '3.8'

services:
  kqsfl-overlay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kqsfl-overlay
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - overlay_network

networks:
  overlay_network:
    driver: bridge