# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
theme: auto
default_redirection_url: https://auth.example.com/ # Change me!

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    path: /config/users_database.yml

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
  issuer: example.com # Change me!

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: two_factor

# Session https://www.authelia.com/configuration/session/introduction/
# Set also AUTHELIA_SESSION_SECRET_FILE
session:
  domain: example.com # Change me!

    # https://www.authelia.com/configuration/session/redis/
    # Set also AUTHELIA_SESSION_REDIS_PASSWORD_FILE if appropriate
  redis:
    host: redis
    port: 6379

storage:
  local:
    path: '/config/db.sqlite3'

# # Storage https://www.authelia.com/configuration/storage/postgres/
# # Set also AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
# # Set also AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
# storage:
#   postgres:
#     host: database
#     database: authelia
#     username: authelia

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'