- name: kasmvnc get current release
  ansible.builtin.get_url:
    url: https://github.com/kasmtech/KasmVNC/releases/download/v{{kasmvnc_version}}/kasmvncserver_{{ansible_distribution_release}}_{{kasmvnc_version}}_amd64.deb
    dest: /tmp/kasmvnc.deb

- name: kasmvnc install current release
  ansible.builtin.apt:
    deb: /tmp/kasmvnc.deb

- name: kasmvnc add user to ssl-cert group
  ansible.builtin.user:
    name: "{{ kasmvnc_user }}"
    groups: ssl-cert
    append: yes

- name: kasmvnc configure user password
  become: yes
  become_user: "{{kasmvnc_user}}"
  ansible.builtin.expect:
    command: "vncpasswd  -u {{kasmvnc_user}} -w -r"
    responses:
      'Password:': "{{kasmvnc_password}}"
      'Verify:': "{{kasmvnc_password}}"

- name: create admin user vnc config directory
  ansible.builtin.file:
    path: "/home/{{kasmvnc_user}}/.vnc"
    state: directory
    owner: stream-admin

- name: kasmvnc vnc config
  ansible.builtin.template:
    src: kasmvnc_user_config.j2
    dest: .vnc/kasmvnc.yaml 
    owner: stream-admin

- name: kasmvnc preload xstartup for physical display
  # https://github.com/kasmtech/KasmVNC/issues/151
  ansible.builtin.copy:
    src: xstartup-xproxy
    dest: "/home/{{kasmvnc_user}}/.vnc/xstartup"
    owner: stream-admin
    mode: 744
  when: kasmvnc_physical_display

- name: kasmvnc create basic user systemd directory
  ansible.builtin.file:
    path: "/home/stream-admin/.config/systemd/user/"
    state: directory
    owner: stream-admin

- name: kasmvnc create basic user systemd directory
  ansible.builtin.file:
    path: "/home/{{kasmvnc_user}}/.vnc/.de-was-selected"
    state: directory
    owner: stream-admin

- name: kasmvnc configure systemd service
  ansible.builtin.template:
    src: kasmvnc_systemd_service.j2
    dest: /etc/systemd/system/kasmvnc.service

- name: register uid of stream-admin
  command: id -u stream-admin
  register: stream_admin_uid

- name: kasmvnc enable systemd service
  ansible.builtin.systemd:
    service: kasmvnc.service
    enabled: true
    daemon_reload: true
    state: restarted

