#!/bin/bash

# This script prepares a fresh server to be configured with ansible

set -euo pipefail

# To Do: Check for existing versions of dependencies

echo -e '\n\n\n'
echo 'Installing ansible dependencies'
sudo apt update
sudo apt install -y \
   git \
   python3 \
   python3-pip \
   jq \
   openssh-server \
   net-tools
echo 'Dependencies installed'

echo -e '\n\n\n'
echo 'Installing pipx'
sudo apt install pipx
pipx ensurepath
echo 'pipx installed'


echo -e '\n\n\n'
echo 'Installing Ansible'
pipx install --include-deps ansible
pipx ensurepath
. ~/.bashrc
echo 'Ansible installed'

echo -e '\n\n\n'
echo 'You can now complete the rest of the server configuration with ansible'
