- name: update systemd-resolved
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf

- name: restart systemd-resolved
  ansible.builtin.systemd:
    state: restarted
    name: systemd-resolved