- name: install docker
  tags: install_docker
  block:
    - name: streambox docker install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-setuptools
          - python3-pip
        state: latest
        update_cache: true

    - name: streambox docker add an apt signing key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: streambox add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: streambox docker install docker-ce
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: streambox docker allow admin user
      ansible.builtin.user:
        name: "{{streambox_admin_user}}"
        groups: docker
        append: yes

- name: streambox upload primary docker compose
  tags: docker-compose
  block:
    - name: copy streambox docker compose configurations
      ansible.builtin.copy:
        src: streambox-docker/
        dest: /etc/docker/compose/streambox
      tags: streambox_deploy_docker_compose_configs

    - name: streambox deploy docker stack environment variables
      block:
        - name: streambox deploy web-server env_file
          ansible.builtin.template:
            src: webserver.env.j2
            dest: /etc/docker/compose/streambox/web-server/web-server.env
            mode: '0644'
            owner: "{{streambox_admin_user}}"
            group: "{{streambox_admin_user}}"
            backup: yes

    - name: streambox build and download docker images
      community.docker.docker_compose_v2_pull:
        project_src: /etc/docker/compose/streambox/

    - name: start streambox docker cluster
      community.docker.docker_compose_v2:
        project_src: /etc/docker/compose/streambox/
        build: always