# https://kasmweb.com/kasmvnc/docs/master/configuration.html
logging:
  log_writer_name: all
  log_dest: logfile
  level: 100
network:
  protocol: http
  interface: 127.0.0.1
  ssl:
    require_ssl: false
server:
  http:
    headers:
      - Cross-Origin-Embedder-Policy=require-corp
      - Cross-Origin-Opener-Policy=same-origin
    httpd_directory: /usr/share/kasmvnc/www/kasm
  auto_shutdown:
    no_user_session_timeout: never
    active_user_session_timeout: never
    inactive_user_session_timeout: never
