- name: streambox configure rclone with mega.io mount
  ansible.builtin.include_role:
    name: stefangweichinger.ansible_rclone
  vars:
    rclone_config_owner:
      OWNER: stream-admin
      GROUP: stream-admin
    rclone_mkdir: false
    rclone_config_location: "{{rclone_config_dir}}/rclone.conf"
    rclone_configs:
      - name: "{{rclone_mount_name}}"
        properties:
          type: mega
          user: "{{streambox_rclone_mega_user}}"
          pass: "{{streambox_rclone_mega_password}}"
          use_https: true
          description: "connect to mega.io drive"