#streambox_rclone_gdrive_sa_email:
#streambox_rclone_gdrive_sa_token:
#streambox_rclone_gdrive_client_id:
#streambox_rclone_gdrive_client_secret:
#streambox_rclone_gdrive_oauth_token:
#streambox_rclone_gdrive_use_oauth: true
#streambox_rclone_gdrive_sa_cred_filename: obs-service-account.json



- name: streambox configure google drive sync for obs backups
  tags: configure_gdrive
  block:
    - name: streambox configure rclone with GDrive mount
      ansible.builtin.include_role:
        name: stefangweichinger.ansible_rclone
        # https://rclone.org/drive/#making-your-own-client-id
      vars:
        rclone_config_owner:
          OWNER: stream-admin
          GROUP: stream-admin
        rclone_config_location: "/home/stream-admin/.config/rclone/rclone.conf"
        rclone_configs:
          - name: gdrive-obs
            properties:
              type: drive
              scope: drive
              metadata_labels: read,write
              root_folder_id: "{{streambox_rclone_gdrive_root_folder}}"
              client_id: "{{streambox_rclone_gdrive_client_id  | mandatory}}"
              client_secret: "{{streambox_rclone_gdrive_client_secret  | mandatory}}"
              token: "{{streambox_rclone_gdrive_oauth_token  | mandatory | to_json}}"
              description: connect to gdrive using oauth as a real authorized user
      when: streambox_rclone_gdrive_use_oauth|bool

    - name: streambox configure rclone with GDrive mount
      ansible.builtin.include_role:
        name: stefangweichinger.ansible_rclone
        # https://rclone.org/drive/#making-your-own-client-id
      vars:
        rclone_config_owner:
          OWNER: stream-admin
          GROUP: stream-admin
        rclone_config_location: "/home/stream-admin/.config/rclone/rclone.conf"
        rclone_configs:
          - name: gdrive-obs
            properties:
              type: drive
              scope: drive
              metadata_labels: read,write
              root_folder_id: "{{streambox_rclone_gdrive_root_folder}}"
              shared_with_me: true
              service_account_credentials: "{{streambox_rclone_gdrive_sa_token | mandatory | to_json}}"
              description: connect to gdrive using service account
      when: not streambox_rclone_gdrive_use_oauth|bool