---
- name: configure streambox server
  hosts: localhost
  # run locally using the following command
  # ansible-playbook -K -u "$USER" -c local streambox.yml
  connection: local
  become: yes
  become_user: root

  tasks:
    - name: test
      command: whoami

    - name: configure google drive sync
      block:
        - name: install rclone
          ansible.builtin.include_role:
            name: stefangweichinger.ansible_rclone
          vars:
            rclone_version: "1.68.1"
            # Versions listed at https://github.com/rclone/rclone/releases

        - name: create mount point
          file:
            path: /opt/kqsfl-stream/local-recording-backups
            state: directory  

        - name: configure rclone with GDrive mount
          ansible.builtin.include_role:
            name: stefangweichinger.ansible_rclone
          vars:
            rclone_configs:
              - name: google-drive
                properties:
                  type: drive
                  token: 
                  client_id: 
                  client_secret:
          when: false # Temporarily disabling until credentials are available for testing

        - name: Restart rclone
          ansible.builtin.systemd:
            name: rclone.service
            state: restarted
          when: setup_rclone_config.changed

    - name: install obs studio
      # https://obsproject.com/kb/linux-installation
      block:
        - name: obs studio add apt repo
          ansible.builtin.apt_repository:
            repo: ppa:obsproject/obs-studio

        - name: obs studio install
          ansible.builtin.apt:
            update_cache: yes
            name: obs-studio=30.2.3-0obsproject1~noble
            # versions: https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio

    - name: install restreamer
      block:
      - name: install restreamer
        debug: msg='install restreamer'

      - name: configure restreamer
        debug: msg='configure restreamer'

  
