---
- name: configure streambox server
  hosts: streambox
  become: yes
  become_user: root
  vars_files:
    - "{{ lookup('env', 'HOME') }}/streambox_vars.yml"
    - "{{ lookup('env', 'HOME') }}/streambox_credentials.yml"

  roles:
    - streambox

- name: configure obs server
  hosts: obs-server
  become: yes
  become_user: root
  vars_files:
    - "{{ lookup('env', 'HOME') }}/streambox_vars.yml"
    - "{{ lookup('env', 'HOME') }}/streambox_credentials.yml"
  roles:
    - obs-server