---
- name: configure streambox server
  hosts: localhost
  # run locally using the following command
  # ansible-playbook -K -u "$USER" -c local streambox.yml
  connection: local
  become: yes
  become_user: root
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.streambox_vars.yml"
    - "{{ lookup('env', 'HOME') }}/.streambox_credentials.yml"

  role:
    - streambox