####################################################################################
# docker-compose file for (mostly) headless obs
# created by KQSFL 2024
####################################################################################
#
# What does this file do?
#
# Using docker-compose it will:
#
#####################################################################################

#version: '3.0'

networks:
  streambox_compose:
    driver: bridge

services:
  obs-server:
    container_name: obs-server
    image: obs-server
    build: ./obs-server
    pull_policy: never
    init: true
    restart: unless-stopped
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=${KASM_VNC_PASSWORD}
    shm_size: 512m
    volumes:
      - ${HOME}/obs-studio:/home/kasm-user/.config/obs-studio
      - ${HOME}/mnt/gdrive-obs/:/home/kasm-user/mnt/gdrive-obs
      - /dev/dri:/dev/dri
    networks:
      - streambox_compose
#    deploy:
      # https://www.doscher.com/gpu-passthrough-for-intel/
#      resources:
#        reservations:
#         devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:443:443/udp"
    volumes:
      - ./webserver/Caddyfile:/etc/caddy/Caddyfile
      - ./webserver/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - streambox_compose
    extra_hosts:
      - "host.docker.internal:host-gateway"

  olivetin:
    # https://docs.olivetin.app/install-compose.html
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./olivetin/config:/config
    ports:
      - "1337:1337"
    restart: unless-stopped

  restreamer:
    # https://docs.olivetin.app/install-compose.html
    container_name: restreamer
    image: datarhei/restreamer
#    volumes:
#    ports:
#    restart: unless-stopped

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    networks:
      - streambox_compose
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be enabled.
      disable: true

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - streambox_compose
    expose:
      - 6379
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  redis_data: