####################################################################################
# docker-compose file for (mostly) headless obs
# created by KQSFL 2024
####################################################################################
#
# What does this file do?
#
# Using docker-compose it will:
#
#####################################################################################

#version: '3.0'

networks:
  streambox_compose:
    driver: bridge
  streambox_auth:
    driver: overlay

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./webserver/conf:/etc/caddy/
      - ./webserver/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - streambox_compose
      - streambox_auth
    extra_hosts:
      - "host.docker.internal:host-gateway"

  obs-server:
    container_name: obs-server
    image: obs-server
    build: ./obs-server
    pull_policy: never
    init: true
    restart: unless-stopped
    expose:
      - 6901
    environment:
      - VNC_PW=${KASM_VNC_PASSWORD}
    shm_size: 512m
    volumes:
      - ${HOME}/obs-studio:/home/kasm-user/.config/obs-studio
      - ${HOME}/mnt/gdrive-obs/:/home/kasm-user/mnt/gdrive-obs
      - /dev/dri:/dev/dri
    networks:
      - streambox_compose
#    deploy:
      # https://www.doscher.com/gpu-passthrough-for-intel/
#      resources:
#        reservations:
#         devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

  olivetin:
    # https://docs.olivetin.app/install-compose.html
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./olivetin/config:/config
    expose:
      - 1337
    restart: unless-stopped

  restreamer:
    # https://docs.olivetin.app/install-compose.html
    container_name: restreamer
    image: datarhei/restreamer
#    volumes:
#    ports:
#    restart: unless-stopped

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia/config:/config
    networks:
      - streambox_auth
    expose:
      - 9091:9091
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be enabled.
      disable: true
    environment:
      AUTHELIA_JWT_SECRET_FILE: /config/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/SESSION_SECRET
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/secrets/SMTP_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /config/secrets/STORAGE_PASSWORD
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /config/secrets/REDIS_PASSWORD

  # auth_database:
  #   container_name: auth_database
  #   image: postgres:15
  #   restart: unless-stopped
  #   volumes:
  #     - auth_database:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: "authelia"
  #     POSTGRES_PASSWORD: ${AUTHDB_ADMIN_PASSWORD}

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - streambox_compose
    expose:
      - 6379:6379
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  redis_data:
  auth_database: