# rclone configure cloud drive sync for obs backups
# https://rclone.org/commands/rclone_mount/
- name: rclone install dependencies
  ansible.builtin.apt:
    pkg: fuse3

- name: rclone install
  ansible.builtin.include_role:
    name: stefangweichinger.ansible_rclone
  vars:
    rclone_version: "{{streambox_rclone_version}}"
    # Versions listed at https://github.com/rclone/rclone/releases

- name: rclone create mount directory
  file:
    path: "{{streambox_rclone_mount_point}}"
    state: directory
    owner: stream-admin

- name: rclone configure and mount remote storage
  import_tasks: mounts/rclone_megaio.yml